### ISSUE TITLE
Add test coverage reporting (and uploading to codecov)?

### ISSUE THREAD

**Issue by Liamsi** [interchainio/tendermint-rs#133]
We could look into https://github.com/libra/libra/blob/ead737947aa59499ea75b5a926d221ac089ce803/.circleci/config.yml#L51-L58
and 
https://github.com/libra/libra/blob/ead737947aa59499ea75b5a926d221ac089ce803/scripts/coverage_report.sh#L97-L104
for a good example how to do this.

**Comment by tarcieri** [comment]
You might also check out [Tarpaulin](https://crates.io/crates/cargo-tarpaulin)

**Comment by Liamsi** [comment]
Thanks, will look into it, too. Would Tarpulin your tool of choice here?

**Comment by tarcieri** [comment]
It's the main one I've worked with in the past. I know some people have had issues with it, but it seems fairly popular.

**Comment by Liamsi** [comment]
Just to visualize this a little; this is output generated via grcov (generated on branch ismail/light_cleanup, commit 7012553191bdbeb71d0ef9751b1e9935fe23d8d3)
![image](https://user-images.githubusercontent.com/7441766/73185834-188e6c00-411f-11ea-81b3-bdd5d86c3b3e.png)
file view:
![image](https://user-images.githubusercontent.com/7441766/73186240-aec29200-411f-11ea-8345-a8f3e1ef49fd.png)

Both Tarpulin and grcov can report the diff (locally and via coverall.io for instance)
(example project using Tarpulin: https://coveralls.io/github/xd009642/keygraph-rs?branch=master)

Tarpulin doesn't run natively on Macs but docker images are provided. In general Tarpulin seems a bit easier to use to me. 

P.S. IntelliJ (never disappoints me and) has test coverage reporting integrated into the IDE. They use grcov apparently. I have a slight preference for grcov as numbers reported by the CI will match my local way of detecting test-coverage but that's probably not the best reason :-D

**Comment by Liamsi** [comment]
Closed via #134 (with grcov; if need arises we can switch to another code coverage tool)
Another issue deals with CI #135
