### ISSUE TITLE
More data in light client errors

### ISSUE THREAD

**Issue by ebuchman** [interchainio/tendermint-rs#139]
Follow up to #110 Errors.

- [x] `Error::RequestFailed` should wrap underlying requester errors (https://github.com/interchainio/tendermint-rs/pull/100#discussion_r360341870)
- [x] Other error types should wrap relevant data
- [x] Remove `Error::InvalidSignature`? It's not used directly by the `light` package, only by implementations

**Comment by Liamsi** [comment]
I'll give this a stab shortly.

**Comment by Liamsi** [comment]
Reopened because `InvalidSignature` part still needs addressing.

**Comment by Liamsi** [comment]
The last todo was addressed in #151. This can be closed now.
