### ISSUE TITLE
Light client voting_power_in can't detect invalid signers

### ISSUE THREAD

**Issue by ebuchman** [interchainio/tendermint-rs#140]
Follow up to one point in #110:

The `voting_power_in` method can't detect signatures from validators not in the current validator set. While this isn't really a big deal, since we can't be fooled into accepting something that wasn't correctly signed, there is no good reason for us to receive a commit with a signature from a validator who's not in the validator set, and thus we should be able to detect it and mark the full node we got it from as faulty.

**Comment by Liamsi** [comment]
Seems related: https://github.com/interchainio/tendermint-rs/pull/143#discussion_r374958528
