### ISSUE TITLE
Failure crate: "soft ecosystem deprecated"

### ISSUE THREAD

**Issue by Liamsi** [interchainio/tendermint-rs#150]
- Related discussion: https://github.com/interchainio/tendermint-rs/pull/149#issuecomment-584448738

- Reasoning in abscissa repo: https://github.com/iqlusioninc/abscissa/issues/144

- Good read: https://blog.yoshuawuyts.com/error-handling-survey/

Currently:
https://github.com/interchainio/tendermint-rs/blob/f9287e04ee84e6659ea209529a1bb700ab53e45b/tendermint/Cargo.toml#L36

Used in:
 - [ ] tendermint-rs/error.rs 
 - [ ] tendermint-rs/amino_types/validate.rs
 - [ ] tendermint-rs/rpc/error.rs

We should switch to a combination of thiserror + anonmaly for the whole code base as done in #151 and #149 for the light client module.

**Comment by Liamsi** [comment]
I think we should use `thiserror` to replace the dependency on the failure derives. To have a single error-type for the light client lib (which methods can return instead of an enum variant) `anomaly` looks like a very minimalistic, very good choice.

We could, of course, write a bunch of boilerplate code ourself and not depend on any other lib but this will eat our time for no good reason.

ref related issue: #139.
https://github.com/dtolnay/thiserror
https://docs.rs/anomaly/0.2.0/anomaly/

**Comment by xla** [comment]
> I think we should use `thiserror` to replace the dependency on the failure derives. To have a single error-type for the light client lib (which methods can return instead of an enum variant) `anomaly` looks like a very minimalistic, very good choice.

What does that mean for the error type itself in the light module, will it be modeled like in the anomaly example and carry an enum kind?
> We could, of course, write a bunch of boilerplate code ourself and not depend on any other lib but this will eat our time for no good reason.

What is the typical boilerplate code we would have to maintain? I think it's important to know the cost/downsize.

> ref related issue: #139.
> https://github.com/dtolnay/thiserror
> https://docs.rs/anomaly/

**Comment by Liamsi** [comment]
> What does that mean for the error type itself in the light module, will it be modeled like in the anomaly example and carry an enum kind?

We have an enum with different errors (ErrorKind) anyways because we want to differentiate different errors.

> What is the typical boilerplate code we would have to maintain? I think it's important to know the cost/downsize.

See for example: https://doc.rust-lang.org/src/std/io/error.rs.html#91-174

**Comment by Liamsi** [comment]
For an example using thiserror only see: https://github.com/interchainio/tendermint-rs/blob/e181405c9786becec3ad0f2e86d50466eae08674/tendermint/src/lite/errors.rs
or #149 in its current state (going change in a bit but won't force push).

**Comment by Liamsi** [comment]
With issue #139 and PR #149 we introduced using [`thiserror`](https://github.com/dtolnay/thiserror) and [`anomaly`](https://crates.io/crates/anomaly).
The main motivation was, as Tony mentioned in https://github.com/interchainio/tendermint-rs/pull/149#issuecomment-584448738, the [`failure`](https://boats.gitlab.io/failure/) crate is kinda deprecated.

On the other hand, in #149, the combination of `thiserror`+`anomaly` proved to be useful, pragmatic and straightforward to use. In the light of this changes made to the error handling for the light client, it's worth looking into error handling in the whole repo. Not sure this worth writing up a whole ADR but it's definitely good to document the patterns used. This comment tries to serve  exactly this purpose.

PR #158 makes error handling consistent across modules in this crate. The pattern used can be briefly described as follows:
All error modules now use the combination of `thiserror` and `anomaly`: every error module has a type `Error` which simply is a type alias to `anomaly::BoxError` <sup>[[1]](#exception)</sup>. Additionally, to the `Error` each module has different `Kind` of errors. 
The caller can use the different `Kind`s to properly handle the different errors as they please and for managing control flow. See [here](https://github.com/interchainio/tendermint-rs/blob/4eb88a2288894c2a6409fbc1ef1c3f28ad79a5bc/tendermint/src/lite/verifier.rs#L368-L373) for an example on how to get the `Kind` out of an `Error` and where this is used for control flow purposes. If another error is wrapped, the wrapped error is accessible via `source`.
See [here](https://github.com/interchainio/tendermint-rs/blob/4eb88a2288894c2a6409fbc1ef1c3f28ad79a5bc/tendermint/src/lite/error.rs#L113-L126) how this looks like in practice.

Where it makes sense, e.g., to improve readability, we use the [`fail!`](https://github.com/interchainio/tendermint-rs/blob/4eb88a2288894c2a6409fbc1ef1c3f28ad79a5bc/tendermint/tests/lite.rs#L87), [`format_err!`](https://github.com/interchainio/tendermint-rs/blob/eabd772c5d1a4ba11a113db8f404cdd258b35f1e/tendermint/src/config/node_key.rs#L31-L36),
or [`ensure!`](https://github.com/interchainio/tendermint-rs/blob/4eb88a2288894c2a6409fbc1ef1c3f28ad79a5bc/tendermint/src/lite/verifier.rs#L41-L48) [macros](https://github.com/iqlusioninc/crates/blob/df12a1958244448633e7735c88e049de633ece65/anomaly/src/macros.rs#L12-L44).
Like macros in general they just save writing some same or similar lines of code over and over.

Additional reading:
 - excellent discussion on similar topic: https://github.com/iqlusioninc/abscissa/issues/144
 - good overview on error handling crates: https://blog.yoshuawuyts.com/error-handling-survey/


<a name="exception">[1]</a>: Actually, there is one exception: The RPC errors need to be encoded in a particular way (see the [go-code](https://github.com/tendermint/tendermint/blob/fb5751d2c597a8239325a9dc293f613b96d295ba/rpc/lib/types/types.go#L138-L142) and its counterpart in [rust](https://github.com/interchainio/tendermint-rs/blob/eabd772c5d1a4ba11a113db8f404cdd258b35f1e/tendermint/src/rpc/error.rs#L8-L18)).
Although anomaly provides serde / JSON encoding for errors, the format is slightly [different](https://github.com/iqlusioninc/crates/blob/df12a1958244448633e7735c88e049de633ece65/anomaly/src/serializer.rs#L13-L34). Hence, we kept the error type together with a bunch of methods which also would be provided by anomaly.
