### ISSUE TITLE
No serialization support for `TrustedState`

### ISSUE THREAD

**Issue by yihuang** [interchainio/tendermint-rs#161]
Since `TrustedState` is supposed to be stored, so it'll need serialization. But users can't implement trait for external types, so it's better to builtin?

**Comment by yihuang** [comment]
Is it good to have serde serialization builtin, I can send the PR if I'll be accepted. ;D

**Comment by Liamsi** [comment]
Yes, I think that would make sense. The only concern I have is that JSON might not be the right encoding for storing that data. 
On the other hand, we are already using serde for `TrustThreshold` inside of   the `lite` module: https://github.com/interchainio/tendermint-rs/blob/2761a9d8cd6eae79eca9d7368a9bc6d1ed4452c3/tendermint/src/lite/types.rs#L90-L91

It's also recommended by the rust api guidelines: https://rust-lang.github.io/api-guidelines/interoperability.html#data-structures-implement-serdes-serialize-deserialize-c-serde

I guess, `TrustedState` is a bit of an edge case struct as it only deals with abstract types, but yes, we need this. Please submit a PR.
