### ISSUE TITLE
Add way of creating a `rpc::Client` without performing a health check

### ISSUE THREAD

**Issue by romac** [interchainio/tendermint-rs#168]
In the `ibc-rs` crate, we need to create a `rpc::Client` in a non-async context in order to store it for later use within a struct, and having `rpc::Client::new` perform an async health check on creation makes this impossible without spawning an executor, and executing the task returned by `new`.

I would suggest renaming the existing method to `new_healthy` and adding a plain `new` method which does not perform a health check.

**Comment by Liamsi** [comment]
resolved in #169
