### ISSUE TITLE
Publicly export more functions from `lite::verifier`

### ISSUE THREAD

**Issue by romac** [interchainio/tendermint-rs#175]
Those would be useful for implementing header verification within light client in the `ibc-rs` crate:

- `is_within_trust_period`
- `validate`
- `verify_commit_full`
- `verify_commit_trusting`

**Comment by ebuchman** [comment]
Why does ibc-rs need to call these directly? One of the goals was for the public interface to be difficult to use incorrectly, so you wouldn't need to string functions like the above together yourself, but could just call the high level functions like `verify_single`
