### ISSUE TITLE
Approach for handling ADRs specific to the Rust implementation

### ISSUE THREAD

**Issue by thanethomson** [interchainio/tendermint-rs#19]
In light of recent discussions regarding the spec and ADR processes for Tendermint, would it make sense to have a `docs` or `adr` folder in the `tendermint-rs` repo to allow us to discuss and record architectural decisions specific to the Rust implementation?

An example of what would require such an ADR: in implementing a reactor-style model in a similar manner to the Go version of Tendermint, should we roll our own again or should we make use of some kind of [Tokio](https://tokio.rs/)-based framework such as [Actix](https://actix.rs/)? And if we go with a framework, how do we create/design/document some kind of interface to it that doesn't lock us into using that particular framework?

**Comment by greg-szabo** [comment]
Let's do this in our new directory structure on the new repository. I'm closing this and referencing #7 so we remember.
