### ISSUE TITLE
Move Secret Connection crate back to KMS

### ISSUE THREAD

**Issue by ebuchman** [interchainio/tendermint-rs#27]
Secret Connection is a bit heavy duty for this library. It's currently needed by the KMS, and will likely see some upgrades in the near term that will need to be closely integrated with the KMS (ie. to support timeouts via async/await - #2). See also the relevant dependency issue #11 and PR #21. 

We likely won't won't need Secret Connection here for a while as we're focusing first on the light client and deterministic simulation of reactors, and by the time we look to integrate with peers, with any luck, a libp2p solution will be ready for Tendermint adoption.

**Comment by tarcieri** [comment]
Moving this back would unblock KMS on #11 and allow us to experiment with solving timeouts with various async strategies

**Comment by tarcieri** [comment]
PR open to move Secret Connection back to the KMS here:

https://github.com/tendermint/kms/pull/365

After that lands, I'd suggest deleting the copy of Secret Connection in-tree and removing *ring* (see #11) and `x25519-dalek` from the dependencies, as this will unblock the Signatory upgrades Dependabot is trying to perform.
