### ISSUE TITLE
RPC incompatibility: SignedHeader does not contain Commit

### ISSUE THREAD

**Issue by Liamsi** [interchainio/tendermint-rs#38]
The struct for the /commit rpc response is currently different from the go-lang implementation. This could be on purpose: commits were or are about to be refactored ([to consist of only signatures](https://github.com/tendermint/tendermint/issues/1648)). 
The light client will talk to the rpc endpoint exposed by tendermint. Hence, the types should now match the go implementation (or introduce a new compatible type exclusively for the light client if desired).

Current `SignedHeader` in Rust:
https://github.com/interchainio/tendermint-rs/blob/5844dc5c0faa537b4225c5221cd863285b97d8ce/tendermint/src/rpc/endpoint/commit.rs#L44-L47

`SignedHeader` in golang:
https://github.com/tendermint/tendermint/blob/51dc810d041eaac78320adc6d53ad8b160b06601/types/block.go#L708-L713

encapsulated in the `ResultCommit ` response:
https://github.com/tendermint/tendermint/blob/51dc810d041eaac78320adc6d53ad8b160b06601/rpc/core/types/responses.go#L34-L37

by this endpoint:
https://github.com/tendermint/tendermint/blob/51dc810d041eaac78320adc6d53ad8b160b06601/rpc/core/blocks.go#L317

ref: #31 #36

**Comment by ebuchman** [comment]
Yeh we need to add a Commit field for this end point thanks for opening an issue
