### ISSUE TITLE
Enable Clippy and fix badges

### ISSUE THREAD

**Issue by Liamsi** [interchainio/tendermint-rs#39]
I've noticed that the badges in the readme still point to those of the kms (license, build).

Also, I think it would be a good idea to enable clippy in circle-ci. The kms repo has an example on howto do so:
https://github.com/tendermint/kms/blob/3b3aabf8eab64959dad29ee2d5b747dc5fe813ac/.circleci/config.yml#L16-L20

**Comment by xla** [comment]
On that note I'd suggest to enable pedantic clippy checks as it helps esp. in with overflows and precision loss for numbers. For someone interested in hardmode:

``` rust
#![deny(missing_docs)]
#![deny(warnings)]
#![forbid(
    clippy::all,
    clippy::cargo,
    clippy::nursery,
    clippy::pedantic,
    clippy::restriction
)]
```
