### ISSUE TITLE
SimpleMerkle / rfc 6962 merkle tree hasher

### ISSUE THREAD

**Issue by Liamsi** [interchainio/tendermint-rs#43]
We need a [`merkle.SimpleHashFromByteSlices `](https://github.com/tendermint/tendermint/blob/51dc810d041eaac78320adc6d53ad8b160b06601/crypto/merkle/simple_tree.go#L9) equivalent in the rust code base to be able to recompute the [hash of the header](https://github.com/tendermint/tendermint/blob/51dc810d041eaac78320adc6d53ad8b160b06601/types/block.go#L393-L415).

This will also be relevant in the light client.

**Comment by Liamsi** [comment]
Maybe @tarcieri has a good suggestion which rust implementation to use here? IMHO if feasible, we should simply use existing implementations.

**Comment by tarcieri** [comment]
Some options:

- [`sct`](https://crates.io/crates/sct): Signed Certificate Timestamp verifier used by `rustls`. Might be too specific to your needs, but is probably the most robust available option if it does.

Here are some other random crates which claim to support RFC 6962 Merkle trees, although I'm not sure any of them are in particularly good shape:

- [`merkle_light`]: https://crates.io/crates/merkle_light
- [`mrkl`]: https://crates.io/crates/mrkl

**Comment by davebryson** [comment]
Just curious, what's wrong with the one in the repo?  https://github.com/interchainio/tendermint-rs/blob/master/tendermint/src/merkle.rs

**Comment by Liamsi** [comment]
Oh no, probably nothing 🙈I didn't notice / know that this was implemented... We'll go with this implementation for sure. Thanks! And sorry for the noise. Closing for now...
