### ISSUE TITLE
Upgrade RPC client to use hyper v0.13 + async/await

### ISSUE THREAD

**Issue by tarcieri** [interchainio/tendermint-rs#78]
The RPC client presently uses a synchronous blocking I/O-based approach, built on a now ancient `hyper` v0.10 as the HTTP client.

Upstream `hyper` is just about to land `tokio` v0.2 support: https://github.com/hyperium/hyper/issues/2025

...and soon thereafter, will hopefully have a v0.13 release with stable-ish `async`/`await`.

When that happens, it'd be great to update the RPC client to use it.

**Comment by tarcieri** [comment]
I got this to almost compile locally. The problem now is the RPC client needs `bytes` v0.5, which is incompatible with `prost`:

```
error[E0277]: the trait bound `B: bytes::buf::buf::Buf` is not satisfied
   --> tendermint/src/validator.rs:118:28
    |
118 | #[derive(Clone, PartialEq, Message)]
    |                            ^^^^^^^ the trait `bytes::buf::buf::Buf` is not implemented for `B`
    |
   ::: /Users/bascule/.cargo/registry/src/github.com-1ecc6299db9ec823/prost-amino-0.4.0/src/encoding.rs:53:75
    |
53  | pub fn decode_varint<B>(buf: &mut B) -> Result<u64, DecodeError> where B: Buf {
    |                                                                           --- required by this bound in `prost::encoding::decode_varint`
    |
    = help: consider adding a `where B: bytes::buf::buf::Buf` bound

error: aborting due to 107 previous errors
```

...so we need to split apart RPC into a separate crate which can depend on `bytes` v0.5

**Comment by Liamsi** [comment]
Looks like upgrading prost (and then prost-amino) to use `bytes` v0.5 is on the way, too: https://github.com/danburkert/prost/issues/242#issuecomment-560245502

**Comment by tarcieri** [comment]
I did find a workaround that doesn't involve splitting the RPC client into a separate crate... I can pull in 2 versions of bytes and give one of them a different name.

However, I'm running into some pretty weird type errors trying to convert the various methods into `async fn`. I can push up my WIP.

**Comment by Liamsi** [comment]
> I did find a workaround that doesn't involve splitting the RPC client into a separate crate... 

Cool! 

> I can push up my WIP.

It would be interesting to peek into an early (draft) PR!

**Comment by tarcieri** [comment]
WIP here: https://github.com/interchainio/tendermint-rs/pull/85

**Comment by Liamsi** [comment]
done in #85
